// <auto-generated>
// Generated by Preset Pro. Manual edits will be overwritten.
// </auto-generated>
using UnityEditor;

namespace PresetPro.Editor
{
    internal static class PresetProGeneratedEditorMenu
    {
        [MenuItem("VFXSkill/预设 Pro/工具介绍", false, 1199)]
        private static void OpenIntro()
        {
            PresetProIntroWindow.OpenWindow();
        }

        [MenuItem("VFXSkill/预设 Pro/设置", false, 1200)]
        private static void OpenSettings()
        {
            PresetProSettingsWindow.OpenWindowInternal(false);
        }

        [MenuItem("VFXSkill/预设 Pro/快速添加", false, 1201)]
        private static void OpenQuickAdd()
        {
            PresetProQuickAddWindow.OpenForCurrentSelection();
        }

        [MenuItem("VFXSkill/预设 Pro/生成菜单", false, 1202)]
        private static void GenerateMenu()
        {
            PresetProMenuGenerator.GenerateAndRefresh(true);
        }
    }
}
