using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace PresetPro.Editor
{
    public static class PresetProMenuGenerator
    {
        public static void GenerateAndRefresh(bool showFeedback = true)
        {
            PresetProSettingsAsset settings = PresetProSettingsProvider.GetOrCreateSettings();
            settings.presetsRoot = PresetProPathUtility.NormalizeAssetFolderPath(settings.presetsRoot);
            settings.SanitizeMenuSettings();
            if (!PresetProPathUtility.IsAssetPathInsideProject(settings.presetsRoot))
            {
                settings.presetsRoot = PresetProPathUtility.DefaultPresetsRoot;
            }

            PresetProPathUtility.EnsureAssetFolderExists(settings.presetsRoot);
            PresetProPathUtility.EnsureAssetFolderExists(PresetProPathUtility.GeneratedMenuDirectory);
            PresetProSettingsProvider.SaveSettings(settings);

            List<PresetProCategoryData> categories = PresetProDataScanner.GetCategories(settings);
            string scriptContent = BuildGeneratedMenuScript(settings, categories);
            string editorMenuScriptContent = BuildGeneratedEditorMenuScript(settings);

            string absolutePath = PresetProPathUtility.AssetPathToAbsolutePath(PresetProPathUtility.GeneratedMenuScriptPath);
            Directory.CreateDirectory(Path.GetDirectoryName(absolutePath) ?? string.Empty);
            File.WriteAllText(absolutePath, scriptContent, new UTF8Encoding(false));

            string editorMenuAbsolutePath = PresetProPathUtility.AssetPathToAbsolutePath(PresetProPathUtility.GeneratedEditorMenuScriptPath);
            Directory.CreateDirectory(Path.GetDirectoryName(editorMenuAbsolutePath) ?? string.Empty);
            File.WriteAllText(editorMenuAbsolutePath, editorMenuScriptContent, new UTF8Encoding(false));

            AssetDatabase.ImportAsset(PresetProPathUtility.GeneratedMenuScriptPath, ImportAssetOptions.ForceUpdate);
            AssetDatabase.ImportAsset(PresetProPathUtility.GeneratedEditorMenuScriptPath, ImportAssetOptions.ForceUpdate);
            AssetDatabase.Refresh(ImportAssetOptions.ForceUpdate);

            if (showFeedback)
            {
                int itemCount = 0;
                for (int i = 0; i < categories.Count; i++)
                {
                    itemCount += categories[i].prefabs.Count;
                }

                string prefix = PresetProLocalization.Choose(
                    settings,
                    "预设 Pro: 菜单生成完成。",
                    "Preset Pro: menu generated.");
                Debug.Log($"{prefix} Categories={categories.Count}, Presets={itemCount}");
            }
        }

        private static string BuildGeneratedEditorMenuScript(PresetProSettingsAsset settings)
        {
            bool useChinese = PresetProLocalization.UseChinese(settings);
            string introLabel = useChinese ? "工具介绍" : "Introduction";
            string settingsLabel = useChinese ? "设置" : "Settings";
            string quickAddLabel = useChinese ? "快速添加" : "Quick Add";
            string generateLabel = useChinese ? "生成菜单" : "Generate Menu";
            string rootLabel = useChinese ? "VFXSkill/预设 Pro" : "VFXSkill/Preset Pro";

            var sb = new StringBuilder(512);
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by Preset Pro. Manual edits will be overwritten.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using UnityEditor;");
            sb.AppendLine();
            sb.AppendLine("namespace PresetPro.Editor");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class PresetProGeneratedEditorMenu");
            sb.AppendLine("    {");
            sb.AppendLine($"        [MenuItem(\"{PresetProNameUtility.EscapeCSharpString(rootLabel + "/" + introLabel)}\", false, 1199)]");
            sb.AppendLine("        private static void OpenIntro()");
            sb.AppendLine("        {");
            sb.AppendLine("            PresetProIntroWindow.OpenWindow();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        [MenuItem(\"{PresetProNameUtility.EscapeCSharpString(rootLabel + "/" + settingsLabel)}\", false, 1200)]");
            sb.AppendLine("        private static void OpenSettings()");
            sb.AppendLine("        {");
            sb.AppendLine("            PresetProSettingsWindow.OpenWindowInternal(false);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        [MenuItem(\"{PresetProNameUtility.EscapeCSharpString(rootLabel + "/" + quickAddLabel)}\", false, 1201)]");
            sb.AppendLine("        private static void OpenQuickAdd()");
            sb.AppendLine("        {");
            sb.AppendLine("            PresetProQuickAddWindow.OpenForCurrentSelection();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        [MenuItem(\"{PresetProNameUtility.EscapeCSharpString(rootLabel + "/" + generateLabel)}\", false, 1202)]");
            sb.AppendLine("        private static void GenerateMenu()");
            sb.AppendLine("        {");
            sb.AppendLine("            PresetProMenuGenerator.GenerateAndRefresh(true);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string BuildGeneratedMenuScript(PresetProSettingsAsset settings, List<PresetProCategoryData> categories)
        {
            var sb = new StringBuilder(1024);
            var usedMethodNames = new HashSet<string>();
            var fullMenuPathCount = new Dictionary<string, int>();
            string missingPrefabPrefix = PresetProLocalization.Choose(settings, "预设 Pro: 找不到预制体资源: ", "Preset Pro: Missing prefab asset: ");
            string instantiateFailedPrefix = PresetProLocalization.Choose(settings, "预设 Pro: 预制体实例化失败: ", "Preset Pro: Failed to instantiate prefab: ");
            string undoPrefix = PresetProLocalization.Choose(settings, "创建 ", "Create ");

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by Preset Pro. Manual edits will be overwritten.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using UnityEditor;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace PresetPro.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class PresetProGeneratedMenu");
            sb.AppendLine("    {");

            int priority = 10;
            int generatedCount = 0;
            string menuRoot = PresetProNameUtility.SanitizeMenuLabel(settings.GetGameObjectMenuRoot(), PresetProSettingsAsset.DefaultGameObjectMenuRoot);
            for (int c = 0; c < categories.Count; c++)
            {
                PresetProCategoryData category = categories[c];
                if (category.prefabs.Count == 0)
                {
                    continue;
                }

                string categoryLabel = PresetProNameUtility.SanitizeMenuLabel(category.displayName, category.folderName);
                sb.AppendLine("        // " + categoryLabel);
                for (int p = 0; p < category.prefabs.Count; p++)
                {
                    PresetProPrefabData prefab = category.prefabs[p];
                    string basePrefabLabel = PresetProNameUtility.SanitizeMenuLabel(prefab.name, "Preset");
                    string baseMenuPath = "GameObject/" + menuRoot + "/" + categoryLabel + "/" + basePrefabLabel;
                    int count;
                    if (!fullMenuPathCount.TryGetValue(baseMenuPath, out count))
                    {
                        count = 0;
                    }

                    count++;
                    fullMenuPathCount[baseMenuPath] = count;
                    string menuPath = count > 1 ? baseMenuPath + " (" + count + ")" : baseMenuPath;
                    string methodBase = "Create_" + PresetProNameUtility.SanitizeMethodName(category.folderName + "_" + prefab.name, "PresetItem");
                    string methodName = GetUniqueMethodName(methodBase, usedMethodNames);
                    string escapedMenuPath = PresetProNameUtility.EscapeCSharpString(menuPath);
                    string escapedPrefabPath = PresetProNameUtility.EscapeCSharpString(prefab.assetPath);

                    sb.AppendLine($"        [MenuItem(\"{escapedMenuPath}\", false, {priority})]");
                    sb.AppendLine($"        private static void {methodName}(MenuCommand menuCommand)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>(\"{escapedPrefabPath}\");");
                    sb.AppendLine("            if (prefab == null)");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                Debug.LogError(\"{PresetProNameUtility.EscapeCSharpString(missingPrefabPrefix)}{escapedPrefabPath}\");");
                    sb.AppendLine("                return;");
                    sb.AppendLine("            }");
                    sb.AppendLine();
                    sb.AppendLine("            GameObject instance = (GameObject)PrefabUtility.InstantiatePrefab(prefab);");
                    sb.AppendLine("            if (instance == null)");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                Debug.LogError(\"{PresetProNameUtility.EscapeCSharpString(instantiateFailedPrefix)}\" + prefab.name);");
                    sb.AppendLine("                return;");
                    sb.AppendLine("            }");
                    sb.AppendLine();
                    sb.AppendLine("            GameObjectUtility.SetParentAndAlign(instance, menuCommand != null ? menuCommand.context as GameObject : null);");
                    sb.AppendLine($"            Undo.RegisterCreatedObjectUndo(instance, \"{PresetProNameUtility.EscapeCSharpString(undoPrefix)}\" + instance.name);");
                    sb.AppendLine("            Selection.activeObject = instance;");
                    sb.AppendLine("        }");
                    sb.AppendLine();

                    generatedCount++;
                    priority++;
                }
            }

            if (generatedCount == 0)
            {
                sb.AppendLine("        // No preset menu items found.");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string GetUniqueMethodName(string baseName, HashSet<string> used)
        {
            string candidate = baseName;
            int suffix = 2;
            while (!used.Add(candidate))
            {
                candidate = baseName + "_" + suffix;
                suffix++;
            }

            return candidate;
        }
    }
}
